apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscicd
  labels:
    app: devopscicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopscicd
  template:
    metadata:
      labels:
        app: devopscicd
    spec: 
      containers:
      - name: devopscicd
        image: elampari/devopscicd:7
        ports:
        - containerPort: 8080
